### ISSUE TITLE
Port Address Issues Perhaps?

### ISSUE THREAD

**Issue by RightsandWrongsgit** [Lullabot/jenkins-docker-drupal#1]
I installed VirtualBox, Vagrant, and Git; then closed the code and followed the Read Me instructions.  Vagrant Up seemed to run; although I had a Port Address issue on the first attempt and changed the 8080 to 1234 as the example instruction from the error trigger in the code says.  Screenshots of the VirtualBox shows the three installed images; two of which are running following the Vagrant install.  For the two running images; one for Jenkins and the other for Drupal, the Port Mapping is also shown in additional images.

When I attempt to use the iOS local browser addresses in the Read Me file, I get error pages. (I also tired the Windows Port specific examples and got the same).   When I simply do the 'Show' from the Virtual Box Manager for the running images I get command lines for Ubantu and for Jenkins with a prompt for user and password.  I tried the Jenkins prompt with "Admin" as the Users and the Vagrant install generated password and got 'incorrect' errors with several attempts to assure it wasn't just sloppy typing.  

Any suggestions on what is not working?  Are there additional instructions steps I am not aware of?  Are there likely files being called in the Vagrant Up step that are not working?  

<img width="992" alt="Screen Shot 2020-10-08 at 9 22 36 PM" src="https://user-images.githubusercontent.com/48891049/95531239-0e12ba80-09ae-11eb-8341-ff4cef56cfe7.png">
<img width="997" alt="Screen Shot 2020-10-08 at 9 22 52 PM" src="https://user-images.githubusercontent.com/48891049/95531248-0fdc7e00-09ae-11eb-9555-758e8f569d9b.png">
<img width="978" alt="Screen Shot 2020-10-08 at 9 23 40 PM" src="https://user-images.githubusercontent.com/48891049/95531251-10751480-09ae-11eb-8ef2-d001c8b9729e.png">
<img width="971" alt="Screen Shot 2020-10-08 at 9 24 14 PM" src="https://user-images.githubusercontent.com/48891049/95531252-10751480-09ae-11eb-88d4-01569e96768f.png">

**Comment by deviantintegral** [comment]
> iOS local browser addresses in the Read Me file, I get error pages.

iOS? By default, these services will only work from the host machine, and not other devices on your network. Try a browser on your computer.

> I tried the Jenkins prompt with "Admin" as the Users and the Vagrant install generated password

That password is for the Jenkins web UI, so you'll need to get that to load first. For command line access, the default for all vagrant machines everywhere is `vagrant / vagrant`. You can also run `vagrant ssh <drupal|jenkins>` in the directory with the git checkout.
